# Generated by Django 4.0.2 on 2022-02-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dateOJ',
            new_name='Doj',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='docId',
            new_name='docID',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='email',
            new_name='emailID',
        ),
    ]
