# Generated by Django 4.0.2 on 2022-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_date_appointment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='docNanme',
            field=models.CharField(default='test name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patName',
            field=models.CharField(default='pat name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
