# Generated by Django 4.0.2 on 2022-02-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_docnanme_appointment_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patName',
            field=models.CharField(default='pat_name', max_length=100),
            preserve_default=False,
        ),
    ]
