export const specialities = [
  'Dermatology',
  'Endocrinology',
  'Emergency Medicine Specialist',
  'Family Physician',
  'Gastroenterology',
  'Geriatric Medicine Specialist',
  'Nephrology',
  'Neurology',
  'Obstetrics and Gynaecology',
  'Oncology',
  'Ophthalmology',
  'Podiatric Surgeon',
  'Preventive Medicine Specialist',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Rheumatology',
  'Allergy/Immunology',
  'Anesthesiology',
  'Cardiology',
  'Colon and Rectal Surgery',
  'Critical Care Medicine Specialist',
  'Hematology',
  'Hospice and Palliative Medicine Specialist',
  'Infectious Disease Specialist',
  'Internist',
  'Medical Geneticist',
  'Osteopathy ',
  'Otolaryngology',
  'Pathology',
  'Pediatrics',
  'Physiatrist',
  'Plastic Surgery',
  'Sleep Medicine Specialist',
  'Sports Medicine Specialist',
  'General Surgeon',
  'Urology',
];
